[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'forge-cache'
solc_version = "0.8.10"
sender = "0xC24CD15a620b88aF598903e99d010d704EA64b6f"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
